### ISSUE TITLE
smart ups snmp card diagram

### ISSUE THREAD

**Issue by yuri622302** [AleksandrBraun/Smart-UPS-SNMP-Card#1]
Hello. could you please publish the circuit diagram of the smart upd snmp card

**Comment by AleksandrBraun** [comment]
Hi.
[Sheet1.pdf](https://github.com/AleksandrBraun/Smart-UPS-SNMP-Card/files/14802911/Sheet1.pdf)

**Comment by yuri622302** [comment]
Thank you. I really want to repeat your development. I will raise the fee. Thanks again
